---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime : shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(dplyr)
library(sf)
library(shiny)
library(gridExtra)
library(crosstalk)
library(lubridate)
library(ggplot2)
library(plotly)
library(tidyverse)
library(patchwork)


 hobo_data <- readxl::read_xlsx("Hobo_2020-2022 QUAMPO.xlsx")
  hobo_data$`Date Heure` <- as.Date(hobo_data$`Date Heure`)
  hobo_data$Year <- lubridate::year(hobo_data$`Date Heure`)
  hobo_data <- as.data.frame(hobo_data)
  colnames(hobo_data)[2] <- "Date"
  
  temp_data <- as.data.frame(tapply(hobo_data$Temperature,list(hobo_data$`Date Heure`,hobo_data$Site), mean))
  temp_data$Date <- as.Date(row.names(temp_data))
  row.names(temp_data) <- NULL
  temp_data <- as_tibble(temp_data)

  ## IBR data ====
  ibr_data <- readxl::read_xlsx("2022_IBR_allports.xlsx", sheet = 1)
  ibr_data$IBR <- as.numeric(ibr_data$IBR)
  ibr_data$SD <- as.numeric(ibr_data$SD)
  ibr_data$year <- lubridate::year(gsub(".*(.{4})$", "\\1-01-01", ibr_data$date))
  ibr_data$date <- lubridate::my(ibr_data$date)
  
    #  
  #  stress_data <- readxl::read_xlsx("2022_06_15 moy_sd_biomeffect_col.xlsx")[,-1]
  #  
  #  |>
  #   filter(specie == "limpet")
  # .stress_data$date <- lubridate::my(.stress_data$date)
  
  #   temperature_data <- shiny::reactive({
#   
#   hobo_data[[input$Site]]
# })

   


```

Résultats
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}

filter_select("Sélectionnez un port", "Sélectionnez un port", sd, ~Site, multiple = FALSE)

```

Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE, include=TRUE, , fig.keep='all', fig.show='asis'}
  
      p <- ggplot(sd, aes(x = Date,  y = Temperature)) + geom_line()+ annotate(
"rect",
xmin = as.Date("2019-12-01"), xmax = as.Date("2021-05-01"),
ymin = -Inf, ymax = +Inf, fill = alpha("purple", .25)
      ) + ggtitle("Suivi de température dans les eaux") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Date") + ylab("Température (en °C)")

    plotly::ggplotly(p)
    
```
 
Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE}

id_ports <- c("Saint-Florent", "Ile Rousse", "Calvi", "STARESO")
  lat <- c("42.681846", "42.636572", "42.566667","42.580178")
  long <- c("9.303704","8.935399","8.750000", "8.724331")

  d <- data.frame(id_ports,lat,long)
  d_sf <- sf::st_as_sf(d, coords = c("long","lat"), crs = "WGS84")


 leaflet::leaflet() %>% 
    leaflet::addTiles() %>% 
    leaflet::setView(lng = 8.73, lat = 42, zoom = 7.5) %>%
    leaflet::addMarkers(data = d_sf)
 
```

Information {data-orientation=rows data-icon="fa-info-circle"}
=====================================

### Comment utiliser cet outil ?


### À propos


#### Contact