---
title: "Quampo"
output :
  flexdashboard::flex_dashboard:
    orientation: rows
    leafletmap: true
    mathjax: NULL
    self_contained: FALSE
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(leaflet)
library(dplyr)
library(sf)
library(crosstalk)
library(lubridate)
library(ggplot2)
library(plotly)
library(tidyverse)
library(patchwork)
library(dygraphs)

  hobo_data <- readxl::read_xlsx("Hobo_2020-2022 QUAMPO.xlsx")
  hobo_data$`Date Heure` <- as.Date(hobo_data$`Date Heure`)
  hobo_data$Year <- lubridate::year(hobo_data$`Date Heure`)
  hobo_data <- as.data.frame(hobo_data)
  colnames(hobo_data)[2] <- "Date"
 
  sd    <- crosstalk::SharedData$new(hobo_data)
  
```

Résultats
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}

crosstalk::filter_select("Sélectionnez un port", "Sélectionnez un port", sd, ~Site, multiple = FALSE)

```

Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE, include=TRUE, , fig.keep='all', fig.show='asis'}


dygraphs::dygraph(sd, main = "Température des eaux") %>% 
  dygraphs::dyRangeSelector(dateWindow = c("2019-12-01", "2021-05-01"))
# 
# scatterplot <- plot_ly(sd, x = ~Date, y = ~Temperature) %>%
#   layout(dragmode = "select")
# 
# scatterplot
  
      # p <- ggplot(sd, aes(x = Date,  y = Temperature)) + geom_line()
# + annotate(
# "rect",
# xmin = as.Date("2019-12-01"), xmax = as.Date("2021-05-01"),
# ymin = -Inf, ymax = +Inf, fill = alpha("purple", .25)
#       ) + ggtitle("Suivi de température dans les eaux") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Date") + ylab("Température (en °C)")

    # plotly::ggplotly(p) %>%
    #   plotly::partial_bundle()
    
```
 
Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE}

id_ports <- c("Saint-Florent", "Ile Rousse", "Calvi", "STARESO")
  lat <- c("42.681846", "42.636572", "42.566667","42.580178")
  long <- c("9.303704","8.935399","8.750000", "8.724331")

  d <- data.frame(id_ports,lat,long)
  d_sf <- sf::st_as_sf(d, coords = c("long","lat"), crs = "WGS84")


 leaflet::leaflet() %>% 
    leaflet::addTiles() %>% 
    leaflet::setView(lng = 8.73, lat = 42, zoom = 7.5) %>%
    leaflet::addMarkers(data = d_sf)
 
```
Calvi
=====================================  

L'Île Rousse
=====================================

Saint-Florent
=====================================

STARESO
=====================================  



Information {data-orientation=rows data-icon="fa-info-circle"}
=====================================

### Comment utiliser cet outil ?


### À propos


#### Contact