---
title: "Quampo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)

# Read temperature data
hobo    <- readRDS(file = here::here("data/hobo_data.RDS"))

# Read 
ports_m <- sf::st_read(dsn = here::here("data/ports_markers.shp"))

# Put data in a shared environment
hobo_sd <- crosstalk::SharedData$new(hobo)
  
  
```

Résultats
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}

crosstalk::filter_select("Sélectionnez un port", "Sélectionnez un port", hobo_sd, ~Site, multiple = FALSE)

```

Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE, include=TRUE, , fig.keep='all', fig.show='asis'}


# dygraphs::dygraph(sd, main = "Température des eaux") %>% 
#   dygraphs::dyRangeSelector(dateWindow = c("2019-12-01", "2021-05-01"))
# 
# scatterplot <- plot_ly(sd, x = ~Date, y = ~Temperature) %>%
#   layout(dragmode = "select")
# 
# scatterplot
  
      # p <- ggplot(sd, aes(x = Date,  y = Temperature)) + geom_line()
# + annotate(
# "rect",
# xmin = as.Date("2019-12-01"), xmax = as.Date("2021-05-01"),
# ymin = -Inf, ymax = +Inf, fill = alpha("purple", .25)
#       ) + ggtitle("Suivi de température dans les eaux") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Date") + ylab("Température (en °C)")

    # plotly::ggplotly(p) %>%
    #   plotly::partial_bundle()
    
```
 
Row {data-height=500}
-------------------------------------
###

```{r map}


 leaflet::leaflet() %>%
    leaflet::addTiles() %>%
    leaflet::setView(lng = 8.73, lat = 42, zoom = 7.5) %>%
    leaflet::addMarkers(data = ports_m)

```

Information {data-orientation=rows data-icon="fa-info-circle"}
=====================================

### Comment utiliser cet outil ?


### À propos


#### Contact

<!-- $(document).ready(function () { -->
<!--   FlexDashboard.init({ -->
<!--     theme: "paper", -->
<!--     fillPage: true, -->
<!--     orientation: "columns", -->
<!--     storyboard: false, -->
<!--     defaultFigWidth: 576, -->
<!--     defaultFigHeight: 460, -->
<!--     defaultFigWidthMobile: 360, -->
<!--     defaultFigHeightMobile: 460 -->
<!--   }); -->
<!-- }); -->
