---
title: "Quampo"
output :
  flexdashboard::flex_dashboard:
    orientation: rows
    leafletmap: true
    runtime: shiny
    always allow html : TRUE
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(dplyr)
library(sf)
library(crosstalk)
library(shiny)
library(leaflet)
library(sf)
library(lubridate)
library(ggplot2)
library(plotly)
library(tidyverse)
library(gridExtra)
library(patchwork)

id_ports <- c("Saint-Florent", "Ile Rousse", "Calvi", "STARESO")
  lat <- c("42.681846", "42.636572", "42.566667","42.580178")
  long <- c("9.303704","8.935399","8.750000", "8.724331")

  d <- data.frame(id_ports,lat,long)
  d_sf <- sf::st_as_sf(d, coords = c("long","lat"), crs = "WGS84")
  
  
  hobo_data <- readxl::read_xlsx("Hobo_2020-2022 QUAMPO.xlsx")
  hobo_data$`Date Heure` <- as.Date(hobo_data$`Date Heure`)
  hobo_data$Year <- lubridate::year(hobo_data$`Date Heure`)
 
  temp_data <- as.data.frame(tapply(hobo_data$Temperature,list(hobo_data$`Date Heure`,hobo_data$Site), mean))
  temp_data$Date <- as.Date(row.names(temp_data))
  row.names(temp_data) <- NULL
  temp_data <- as_tibble(temp_data)
  
  # ## IBR data ====
   ibr_data <- readxl::read_xlsx("2022_IBR_allports.xlsx", sheet = 1)
   ibr_data$IBR <- as.numeric(ibr_data$IBR)
   ibr_data$SD <- as.numeric(ibr_data$SD)
   ibr_data$year <- lubridate::year(gsub(".*(.{4})$", "\\1-01-01", ibr_data$date))
   ibr_data$date <- lubridate::my(ibr_data$date)
   
  #  
  #  stress_data <- readxl::read_xlsx("2022_06_15 moy_sd_biomeffect_col.xlsx")[,-1]
  #  
  #  |>
  #   filter(specie == "limpet")
  # .stress_data$date <- lubridate::my(.stress_data$date)
   
  
#   temperature_data <- shiny::reactive({
#   
#   hobo_data[[input$Site]]
# })



```

Résultats
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
# Define inputs
shiny::selectInput(
             inputId = "select_data",
             label   = "Sélectionnez un port",
             choices = id_ports,
             selected = "Calvi"                             
   )

shiny::selectInput(
             inputId = "select_var",
             label   = "Sélectionnez une variable",
             choices = c("Température", "IBR"),
             selected = "Température"                             
   )


```

Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE}

shiny::renderPlot({

if (input$select_var == "Température") {
  
  
      ggplot(temp_data, aes(x = Date,  .data[[input$select_data]])) + geom_line()+ annotate(
"rect",
xmin = as.Date("2019-12-01"), xmax = as.Date("2021-05-01"),
ymin = -Inf, ymax = +Inf, fill = alpha("purple", .25)
      ) + ggtitle("Suivi de température dans les eaux") + theme(plot.title = element_text(hjust = 0.5)) + xlab("Date") + ylab("Température (en °C)")
  
} else {
  
  ibr        <- ibr_data[ibr_data$site %in% input$select_data,]
  ibr_mussel <- ibr[ibr$specie %in% "limpet",]
  ibr_limpet <- ibr[ibr$specie %in% "mussel",]
  

  p1 <- ggplot(ibr_mussel, aes(x = date,  y = IBR)) + geom_errorbar(aes(ymin = IBR-SD, ymax = IBR+SD), width = 0.2) +  xlab("Date") + ylab("IBR pour Mytilus galloprovincialis")
  
  p2 <- ggplot(ibr_limpet, aes(x = date,  y = IBR)) + geom_errorbar(aes(ymin = IBR-SD, ymax = IBR+SD), width = 0.2) +  xlab("Date") +  ylab("IBR pour Mimachlamys varia")
  
  pm <- (p1 + p2) + plot_annotation(title = "Évaluation du risque écologique lors de la biosurveillance\nréalisée dans le projet QUAMPO")  &  theme(plot.title = element_text(hjust = 0.5)) 
  # + theme(plot.title = element_text(hjust = 0.5))
  
  pm
  
  # grid.arrange(p1, p2, ncol=2)
  }

})
  
```
 
Row {data-height=500}
-------------------------------------
###

```{r, echo = FALSE}


 leaflet::leaflet() %>% 
    leaflet::addTiles() %>% 
    leaflet::setView(lng = 8.73, lat = 42, zoom = 7.5) %>%
    leaflet::addMarkers(data = d_sf)
 
  # renderPlot({
  #   temp_data %>% filter(ports_id %in% colnames)
  #   
  #   p <- ggplot2::ggplot(dat, ggplot2::aes(x = `Date Heure`)) +
  #     annotate(
  #       "rect",
  #       xmin = as.Date("2019-12-01"), xmax = as.Date("2021-05-01"),
  #       ymin = -Inf, ymax = +Inf, fill = alpha("purple", .25)
  #     ) +
  #     geom_line(ggplot2::aes(y = Temperature, color = factor(Year))) +
  #     scale_x_date(date_breaks = "2 months", date_labels = "%B") +
  #     ggtitle("Suivi de température dans les eaux") + 
  #     xlab("Date") + 
  #     ylab("Température (en °C)")
  #   p$labels$colour <- "Périodes"
  #   
  #   return(p)
  # })

  

```


Information {data-orientation=rows data-icon="fa-info-circle"}
=====================================

### Comment utiliser cet outil ?


### À propos


#### Contact